import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:lucide_icons_flutter/lucide_icons.dart';

/// Maps the icon-name strings stored on [Category.icon] / [AccountType.icon]
/// to a concrete [IconData] — the curated set offered by [pickableIcons], so
/// every name a category/account-type picker can produce resolves here.
/// Falls back to a generic label icon for anything unrecognized (e.g. an
/// icon name from a future app version, or a row restored from an older
/// backup whose icon set has since changed).
const Map<String, IconData> _iconsByName = {
  'label': LucideIcons.tag,
  'category': LucideIcons.shapes,
  'restaurant': LucideIcons.utensils,
  'shopping_cart': LucideIcons.shoppingCart,
  'directions_car': LucideIcons.car,
  'home': LucideIcons.house,
  'movie': LucideIcons.clapperboard,
  'autorenew': LucideIcons.refreshCw,
  'payments': LucideIcons.banknote,
  'local_grocery_store': LucideIcons.shoppingCart,
  'local_hospital': LucideIcons.cross,
  'school': LucideIcons.school,
  'flight': LucideIcons.plane,
  'fitness_center': LucideIcons.dumbbell,
  'pets': LucideIcons.pawPrint,
  'checkroom': LucideIcons.shirt,
  'sports_esports': LucideIcons.gamepad2,
  'card_giftcard': LucideIcons.gift,
  'build': LucideIcons.wrench,
  'wifi': LucideIcons.wifi,
  'account_balance_wallet': LucideIcons.wallet,
  'savings': LucideIcons.piggyBank,
  'credit_card': LucideIcons.creditCard,
  'trending_up': LucideIcons.trendingUp,
  'account_balance': LucideIcons.landmark,
  'coffee': LucideIcons.coffee,
  'pizza': LucideIcons.pizza,
  'sandwich': LucideIcons.sandwich,
  'cake': LucideIcons.cakeSlice,
  'ice_cream': LucideIcons.iceCreamCone,
  'fruit': LucideIcons.apple,
  'wine': LucideIcons.wine,
  'beer': LucideIcons.beer,
  'fuel': LucideIcons.fuel,
  'bus': LucideIcons.bus,
  'train': LucideIcons.trainFront,
  'bike': LucideIcons.bike,
  'motorbike': LucideIcons.motorbike,
  'taxi': LucideIcons.carTaxiFront,
  'parking': LucideIcons.parkingMeter,
  'ship': LucideIcons.ship,
  'electricity': LucideIcons.zap,
  'water': LucideIcons.droplet,
  'gas': LucideIcons.flame,
  'plug': LucideIcons.plug,
  'smartphone': LucideIcons.smartphone,
  'tv': LucideIcons.tv,
  'sofa': LucideIcons.sofa,
  'bed': LucideIcons.bed,
  'lamp': LucideIcons.lamp,
  'appliance': LucideIcons.refrigerator,
  'laundry': LucideIcons.washingMachine,
  'bath': LucideIcons.bath,
  'tools': LucideIcons.hammer,
  'paint': LucideIcons.paintbrush,
  'garden': LucideIcons.leaf,
  'trash': LucideIcons.trash2,
  'health': LucideIcons.heartPulse,
  'medicine': LucideIcons.pill,
  'doctor': LucideIcons.stethoscope,
  'vaccine': LucideIcons.syringe,
  'eyewear': LucideIcons.glasses,
  'haircut': LucideIcons.scissors,
  'beauty': LucideIcons.sparkles,
  'baby': LucideIcons.baby,
  'shopping_bag': LucideIcons.shoppingBag,
  'store': LucideIcons.store,
  'jewellery': LucideIcons.gem,
  'ticket': LucideIcons.ticket,
  'music': LucideIcons.music,
  'headphones': LucideIcons.headphones,
  'camera': LucideIcons.camera,
  'film': LucideIcons.film,
  'dice': LucideIcons.dice5,
  'trophy': LucideIcons.trophy,
  'party': LucideIcons.partyPopper,
  'newspaper': LucideIcons.newspaper,
  'book': LucideIcons.bookOpen,
  'graduation': LucideIcons.graduationCap,
  'work': LucideIcons.briefcase,
  'laptop': LucideIcons.laptop,
  'office': LucideIcons.building2,
  'bill': LucideIcons.receipt,
  'coins': LucideIcons.coins,
  'salary': LucideIcons.handCoins,
  'interest': LucideIcons.percent,
  'investment': LucideIcons.chartLine,
  'portfolio': LucideIcons.chartPie,
  'crypto': LucideIcons.bitcoin,
  'vault': LucideIcons.vault,
  'insurance': LucideIcons.shield,
  'luggage': LucideIcons.luggage,
  'hotel': LucideIcons.hotel,
  'beach': LucideIcons.palmtree,
  'camping': LucideIcons.tentTree,
  'mountain': LucideIcons.mountain,
  'location': LucideIcons.mapPin,
  'globe': LucideIcons.globe,
  'family': LucideIcons.users,
  'heart': LucideIcons.heart,
  'charity': LucideIcons.handHeart,
  'dog': LucideIcons.dog,
  'cat': LucideIcons.cat,
  'flower': LucideIcons.flower2,
  'calendar': LucideIcons.calendar,
  'smoking': LucideIcons.cigarette,
};

/// Curated icon choices offered when creating/editing a category or account
/// type — every key here must have an entry in [_iconsByName].
const pickableIcons = [
  'label',
  'category',
  'restaurant',
  'shopping_cart',
  'local_grocery_store',
  'directions_car',
  'home',
  'movie',
  'autorenew',
  'payments',
  'local_hospital',
  'school',
  'flight',
  'fitness_center',
  'pets',
  'checkroom',
  'sports_esports',
  'card_giftcard',
  'build',
  'wifi',
  'account_balance_wallet',
  'savings',
  'credit_card',
  'trending_up',
  'account_balance',
  'coffee',
  'pizza',
  'sandwich',
  'cake',
  'ice_cream',
  'fruit',
  'wine',
  'beer',
  'fuel',
  'bus',
  'train',
  'bike',
  'motorbike',
  'taxi',
  'parking',
  'ship',
  'electricity',
  'water',
  'gas',
  'plug',
  'smartphone',
  'tv',
  'sofa',
  'bed',
  'lamp',
  'appliance',
  'laundry',
  'bath',
  'tools',
  'paint',
  'garden',
  'trash',
  'health',
  'medicine',
  'doctor',
  'vaccine',
  'eyewear',
  'haircut',
  'beauty',
  'baby',
  'shopping_bag',
  'store',
  'jewellery',
  'ticket',
  'music',
  'headphones',
  'camera',
  'film',
  'dice',
  'trophy',
  'party',
  'newspaper',
  'book',
  'graduation',
  'work',
  'laptop',
  'office',
  'bill',
  'coins',
  'salary',
  'interest',
  'investment',
  'portfolio',
  'crypto',
  'vault',
  'insurance',
  'luggage',
  'hotel',
  'beach',
  'camping',
  'mountain',
  'location',
  'globe',
  'family',
  'heart',
  'charity',
  'dog',
  'cat',
  'flower',
  'calendar',
  'smoking',
];

/// A curated set of Unicode choices that can be stored alongside Material
/// icon names. Unicode strings are rendered as text by [IconOrEmoji], full
/// colour and expressive where the Lucide set above is deliberately flat and
/// single-tone — offered as a separate "Colorful icons" group in the picker,
/// never mixed into the plain [pickableIcons] one.
const pickableEmojis = [
  '🍽️',
  '🛒',
  '🚗',
  '🏠',
  '🎬',
  '💳',
  '🏥',
  '🎓',
  '✈️',
  '🏋️',
  '🐾',
  '👕',
  '🎮',
  '🎁',
  '🔧',
  '📶',
  '👛',
  '💰',
  '🏦',
  '☕',
  '🎵',
  '📚',
  '❤️',
  '⭐',
  '🔁',
  '🏷️',
  '🐷',
  '💵',
  '📈',
  '💧',
  '💪',
  '🏃',
  '🧘',
  '😴',
  '📓',
  '🚶',
  '⚖️',
  '🤸',
  '🏆',
  '💼',
  '💊',
  '👣',
  '📰',
  '🎥',
  '💡',
  '🪪',
  '🩺',
  '🧾',
  '🗂️',
  '🎂',
  '🍕',
  '🍔',
  '🍜',
  '🍣',
  '🥗',
  '🍳',
  '🍰',
  '🍎',
  '🥦',
  '🥛',
  '🍺',
  '🍷',
  '🧃',
  '⛽',
  '🚌',
  '🚆',
  '🚇',
  '🚲',
  '🛵',
  '🚕',
  '🅿️',
  '🛳️',
  '⚡',
  '🔥',
  '🔌',
  '📱',
  '💻',
  '📺',
  '🛋️',
  '🛏️',
  '🧹',
  '🧺',
  '🪴',
  '🔑',
  '🏡',
  '🦷',
  '👓',
  '💉',
  '🧴',
  '💅',
  '💇',
  '🛍️',
  '👟',
  '👗',
  '💄',
  '💍',
  '⌚',
  '🎉',
  '🎤',
  '🎨',
  '🎲',
  '🎟️',
  '🎧',
  '📷',
  '🎸',
  '⚽',
  '🏏',
  '🏊',
  '👶',
  '🧸',
  '🍼',
  '🐶',
  '🐱',
  '🙏',
  '🤝',
  '🪔',
  '🎄',
  '🚬',
  '💸',
  '🪙',
  '📉',
  '📊',
  '🧮',
  '🏧',
  '📝',
  '✏️',
  '🏖️',
  '🏨',
  '🧳',
  '🗺️',
  '⛰️',
  '🏕️',
];

/// The icon a category carries when none was chosen — matches the `icon`
/// column's own default, and what [resolveIcon] falls back to.
const defaultCategoryIcon = 'label';

IconData resolveIcon(String? name) =>
    _iconsByName[name] ?? _iconsByName[defaultCategoryIcon]!;

/// Blank counts as "no icon", not as an emoji — a row imported from an older
/// backup can carry an empty string, which would otherwise render as nothing.
bool isEmojiIcon(String? value) =>
    value != null && value.isNotEmpty && !_iconsByName.containsKey(value);

/// An emoji, centred the way an [Icon] is.
///
/// A plain [Text] draws an emoji low and a touch left of centre. Fixing the
/// line box is not enough: pinning the height to 1 with even leading centres
/// the font's ascent and descent, but Apple Color Emoji draws its image low
/// and left inside that box regardless — measured on an iPhone, the image
/// centre sat ~0.8pt below and ~0.6pt left of a 20pt glyph's box centre while
/// Lucide icons sat at 0. So Apple platforms get a small optical shift,
/// proportional to [size]. Other platforms are left at the font's own
/// placement until they've been measured.
class EmojiGlyph extends StatelessWidget {
  const EmojiGlyph(this.emoji, {super.key, this.size = 20, this.color});

  final String emoji;
  final double size;
  final Color? color;

  static bool get _isApple =>
      defaultTargetPlatform == TargetPlatform.iOS ||
      defaultTargetPlatform == TargetPlatform.macOS;

  @override
  Widget build(BuildContext context) => Transform.translate(
    offset: _isApple ? Offset(size * 0.03, -size * 0.05) : Offset.zero,
    child: Text(
      emoji,
      textAlign: TextAlign.center,
      style: TextStyle(
        fontSize: size,
        color: color,
        height: 1,
        leadingDistribution: TextLeadingDistribution.even,
      ),
    ),
  );
}

class IconOrEmoji extends StatelessWidget {
  const IconOrEmoji({
    super.key,
    required this.value,
    this.size = 20,
    this.color,
  });
  final String? value;
  final double size;
  final Color? color;

  @override
  Widget build(BuildContext context) => isEmojiIcon(value)
      ? EmojiGlyph(value!, size: size, color: color)
      : Icon(resolveIcon(value), size: size, color: color);
}
