import 'package:flutter/material.dart';

/// Every colour token in the app, from `ui-kit/BRAND_AND_UI_KIT.md` §2.
///
/// GENERATED by `scripts/gen_app_colors.js` — edit the token table there, not
/// this file. The constructor, both const instances, `copyWith` and `lerp` all
/// have to list all 46 fields, and hand-editing four parallel lists is how a
/// colour silently stops animating between themes.
///
/// Three rules from the kit that this encodes:
///
/// * **Semantic colours are per-theme pairs.** An ink that reads on cream is
///   invisible on near-black, so [critical], [warning], [info], [warm] and
///   [deep] each carry two values. Never reuse a light-theme hex in dark.
/// * **Success is [good], which is the accent.** There is no second green.
/// * **Category hues identify things, never state.** The `cat*` and module
///   entries are the same in both themes because they name a thing, not a
///   status. Use them for 14–18% alpha wells, swatches and dots; when one has to
///   carry *text*, use its semantic ink instead — [warm] for the Spend hue,
///   [info] for Water/Calendar, [deep] for Learn.
class AppColors extends ThemeExtension<AppColors> {
  const AppColors({
    required this.finance,
    required this.spend,
    required this.habits,
    required this.tasks,
    required this.documents,
    required this.calendar,
    required this.goals,
    required this.aiAnalyser,
    required this.notes,
    required this.good,
    required this.critical,
    required this.dangerSolid,
    required this.onDanger,
    required this.dangerSoft,
    required this.dangerBd,
    required this.warning,
    required this.warnSoft,
    required this.warnBd,
    required this.warm,
    required this.warmSoft,
    required this.info,
    required this.coolSoft,
    required this.deep,
    required this.deepSoft,
    required this.catDining,
    required this.catGroceries,
    required this.catTransport,
    required this.catRent,
    required this.catShopping,
    required this.catBills,
    required this.catEntertainment,
    required this.catHealth,
    required this.catOther,
    required this.surfaceAlt,
    required this.raised,
    required this.stage,
    required this.text3,
    required this.border2,
    required this.accentSoft,
    required this.accentInk,
    required this.heroA,
    required this.heroB,
    required this.heroVeil,
    required this.heroTrack,
    required this.chrome,
    required this.codeBg,
  });

  // ---- module identity ----
  final Color finance;
  final Color spend;
  final Color habits;
  final Color tasks;
  final Color documents;
  final Color calendar;
  final Color goals;
  final Color aiAnalyser;
  final Color notes;

  // ---- semantic state (per-theme pairs) ----

  /// Success is the accent — the kit is explicit that there is no second green.
  final Color good;

  /// Kit `danger`: destructive labels, overdue, error text.
  final Color critical;

  /// Ground of a filled destructive button.
  final Color dangerSolid;

  /// Ink on [dangerSolid].
  final Color onDanger;

  /// Tinted error wells.
  final Color dangerSoft;

  /// Error borders.
  final Color dangerBd;

  /// Kit `warn`: due soon, low stock, offline.
  final Color warning;
  final Color warnSoft;
  final Color warnBd;

  /// Streaks and outgoing money — the ink for the Spend hue.
  final Color warm;
  final Color warmSoft;

  /// Kit `cool`: water, calendar and medicine glyphs.
  final Color info;
  final Color coolSoft;

  /// Learn and investments.
  final Color deep;
  final Color deepSoft;

  // ---- spend categories (identity) ----
  final Color catDining;
  final Color catGroceries;
  final Color catTransport;
  final Color catRent;
  final Color catShopping;
  final Color catBills;
  final Color catEntertainment;
  final Color catHealth;
  final Color catOther;

  // ---- surfaces and accents ----

  /// Kit `surface-2`: segmented tracks, inset wells.
  final Color surfaceAlt;

  /// Floating chrome — the nav pill, sheets.
  final Color raised;

  /// Behind the app frame; scrim fills.
  final Color stage;

  /// Decorative text only — does not meet 4.5:1 in either theme. Informational
  /// captions use `onSurfaceVariant` (the kit's `text-2`).
  final Color text3;

  /// The lighter hairline, for nested dividers.
  final Color border2;
  final Color accentSoft;
  final Color accentInk;
  final Color heroA;
  final Color heroB;
  final Color heroVeil;
  final Color heroTrack;
  final Color chrome;

  /// Ground behind monospaced code blocks.
  final Color codeBg;

  List<Color> get modulePalette => [
    finance,
    spend,
    habits,
    tasks,
    documents,
    calendar,
    goals,
    aiAnalyser,
    notes,
  ];

  List<Color> get spendCategoryPalette => [
    catDining,
    catGroceries,
    catTransport,
    catRent,
    catShopping,
    catBills,
    catEntertainment,
    catHealth,
    catOther,
  ];

  /// Kit `accent` in light. Feeds `ColorScheme.fromSeed`.
  static const seed = Color(0xFF0E9F6E);

  static const light = AppColors(
    finance: Color(0xFF0E9F6E),
    spend: Color(0xFFC2703D),
    habits: Color(0xFF3FA6A0),
    tasks: Color(0xFF4B7BA6),
    documents: Color(0xFFB0558E),
    calendar: Color(0xFF7C6BC4),
    goals: Color(0xFF3E7C5A),
    aiAnalyser: Color(0xFFD9A441),
    notes: Color(0xFF9A9384),
    good: Color(0xFF0E9F6E),
    critical: Color(0xFFA62F2F),
    dangerSolid: Color(0xFFA62F2F),
    onDanger: Color(0xFFFFFFFF),
    dangerSoft: Color(0x17BE3F3F),
    dangerBd: Color(0x59BE3F3F),
    warning: Color(0xFF8A6410),
    warnSoft: Color(0x21D9A441),
    warnBd: Color(0x4DD9A441),
    warm: Color(0xFF8C4C22),
    warmSoft: Color(0x29C2703D),
    info: Color(0xFF35618A),
    coolSoft: Color(0x294B7BA6),
    deep: Color(0xFF5E4FA8),
    deepSoft: Color(0x297C6BC4),
    catDining: Color(0xFF0E9F6E),
    catGroceries: Color(0xFF3E7C5A),
    catTransport: Color(0xFF4B7BA6),
    catRent: Color(0xFFC2703D),
    catShopping: Color(0xFFB0558E),
    catBills: Color(0xFFD9A441),
    catEntertainment: Color(0xFF7C6BC4),
    catHealth: Color(0xFF3FA6A0),
    catOther: Color(0xFF9A9384),
    surfaceAlt: Color(0xFFFAF6EE),
    raised: Color(0xFFFFFFFF),
    stage: Color(0xFFE7E2D8),
    text3: Color(0xFF9C978C),
    border2: Color(0x0F1C1B18),
    accentSoft: Color(0x1F0E9F6E),
    accentInk: Color(0xFF0B7C56),
    heroA: Color(0xFF0A6E4D),
    heroB: Color(0xFF0C8058),
    heroVeil: Color(0x1AFFFFFF),
    heroTrack: Color(0x47FFFFFF),
    chrome: Color(0xFF0F0F0D),
    codeBg: Color(0xFFF1ECE2),
  );

  static const dark = AppColors(
    finance: Color(0xFF0E9F6E),
    spend: Color(0xFFC2703D),
    habits: Color(0xFF3FA6A0),
    tasks: Color(0xFF4B7BA6),
    documents: Color(0xFFB0558E),
    calendar: Color(0xFF7C6BC4),
    goals: Color(0xFF3E7C5A),
    aiAnalyser: Color(0xFFD9A441),
    notes: Color(0xFF9A9384),
    good: Color(0xFF34D399),
    critical: Color(0xFFF87171),
    dangerSolid: Color(0xFFE05555),
    onDanger: Color(0xFF230A0A),
    dangerSoft: Color(0x21F87171),
    dangerBd: Color(0x57F87171),
    warning: Color(0xFFE3B341),
    warnSoft: Color(0x24E3B341),
    warnBd: Color(0x52E3B341),
    warm: Color(0xFFE09A6B),
    warmSoft: Color(0x26E09A6B),
    info: Color(0xFF8FBBE0),
    coolSoft: Color(0x268FBBE0),
    deep: Color(0xFFB4A7EC),
    deepSoft: Color(0x26B4A7EC),
    catDining: Color(0xFF0E9F6E),
    catGroceries: Color(0xFF3E7C5A),
    catTransport: Color(0xFF4B7BA6),
    catRent: Color(0xFFC2703D),
    catShopping: Color(0xFFB0558E),
    catBills: Color(0xFFD9A441),
    catEntertainment: Color(0xFF7C6BC4),
    catHealth: Color(0xFF3FA6A0),
    catOther: Color(0xFF9A9384),
    surfaceAlt: Color(0xFF2A2823),
    raised: Color(0xFF26241F),
    stage: Color(0xFF0C0B09),
    text3: Color(0xFF736F66),
    border2: Color(0x0DFFFFFF),
    accentSoft: Color(0x2934D399),
    accentInk: Color(0xFF6EE7B7),
    heroA: Color(0xFF34D399),
    heroB: Color(0xFF6EE7B7),
    heroVeil: Color(0x1A0C0B09),
    heroTrack: Color(0x3D0C0B09),
    chrome: Color(0xFFF4F0E7),
    codeBg: Color(0xFF15140F),
  );

  @override
  AppColors copyWith({
    Color? finance,
    Color? spend,
    Color? habits,
    Color? tasks,
    Color? documents,
    Color? calendar,
    Color? goals,
    Color? aiAnalyser,
    Color? notes,
    Color? good,
    Color? critical,
    Color? dangerSolid,
    Color? onDanger,
    Color? dangerSoft,
    Color? dangerBd,
    Color? warning,
    Color? warnSoft,
    Color? warnBd,
    Color? warm,
    Color? warmSoft,
    Color? info,
    Color? coolSoft,
    Color? deep,
    Color? deepSoft,
    Color? catDining,
    Color? catGroceries,
    Color? catTransport,
    Color? catRent,
    Color? catShopping,
    Color? catBills,
    Color? catEntertainment,
    Color? catHealth,
    Color? catOther,
    Color? surfaceAlt,
    Color? raised,
    Color? stage,
    Color? text3,
    Color? border2,
    Color? accentSoft,
    Color? accentInk,
    Color? heroA,
    Color? heroB,
    Color? heroVeil,
    Color? heroTrack,
    Color? chrome,
    Color? codeBg,
  }) {
    return AppColors(
      finance: finance ?? this.finance,
      spend: spend ?? this.spend,
      habits: habits ?? this.habits,
      tasks: tasks ?? this.tasks,
      documents: documents ?? this.documents,
      calendar: calendar ?? this.calendar,
      goals: goals ?? this.goals,
      aiAnalyser: aiAnalyser ?? this.aiAnalyser,
      notes: notes ?? this.notes,
      good: good ?? this.good,
      critical: critical ?? this.critical,
      dangerSolid: dangerSolid ?? this.dangerSolid,
      onDanger: onDanger ?? this.onDanger,
      dangerSoft: dangerSoft ?? this.dangerSoft,
      dangerBd: dangerBd ?? this.dangerBd,
      warning: warning ?? this.warning,
      warnSoft: warnSoft ?? this.warnSoft,
      warnBd: warnBd ?? this.warnBd,
      warm: warm ?? this.warm,
      warmSoft: warmSoft ?? this.warmSoft,
      info: info ?? this.info,
      coolSoft: coolSoft ?? this.coolSoft,
      deep: deep ?? this.deep,
      deepSoft: deepSoft ?? this.deepSoft,
      catDining: catDining ?? this.catDining,
      catGroceries: catGroceries ?? this.catGroceries,
      catTransport: catTransport ?? this.catTransport,
      catRent: catRent ?? this.catRent,
      catShopping: catShopping ?? this.catShopping,
      catBills: catBills ?? this.catBills,
      catEntertainment: catEntertainment ?? this.catEntertainment,
      catHealth: catHealth ?? this.catHealth,
      catOther: catOther ?? this.catOther,
      surfaceAlt: surfaceAlt ?? this.surfaceAlt,
      raised: raised ?? this.raised,
      stage: stage ?? this.stage,
      text3: text3 ?? this.text3,
      border2: border2 ?? this.border2,
      accentSoft: accentSoft ?? this.accentSoft,
      accentInk: accentInk ?? this.accentInk,
      heroA: heroA ?? this.heroA,
      heroB: heroB ?? this.heroB,
      heroVeil: heroVeil ?? this.heroVeil,
      heroTrack: heroTrack ?? this.heroTrack,
      chrome: chrome ?? this.chrome,
      codeBg: codeBg ?? this.codeBg,
    );
  }

  @override
  AppColors lerp(ThemeExtension<AppColors>? other, double t) {
    if (other is! AppColors) return this;
    return AppColors(
      finance: Color.lerp(finance, other.finance, t)!,
      spend: Color.lerp(spend, other.spend, t)!,
      habits: Color.lerp(habits, other.habits, t)!,
      tasks: Color.lerp(tasks, other.tasks, t)!,
      documents: Color.lerp(documents, other.documents, t)!,
      calendar: Color.lerp(calendar, other.calendar, t)!,
      goals: Color.lerp(goals, other.goals, t)!,
      aiAnalyser: Color.lerp(aiAnalyser, other.aiAnalyser, t)!,
      notes: Color.lerp(notes, other.notes, t)!,
      good: Color.lerp(good, other.good, t)!,
      critical: Color.lerp(critical, other.critical, t)!,
      dangerSolid: Color.lerp(dangerSolid, other.dangerSolid, t)!,
      onDanger: Color.lerp(onDanger, other.onDanger, t)!,
      dangerSoft: Color.lerp(dangerSoft, other.dangerSoft, t)!,
      dangerBd: Color.lerp(dangerBd, other.dangerBd, t)!,
      warning: Color.lerp(warning, other.warning, t)!,
      warnSoft: Color.lerp(warnSoft, other.warnSoft, t)!,
      warnBd: Color.lerp(warnBd, other.warnBd, t)!,
      warm: Color.lerp(warm, other.warm, t)!,
      warmSoft: Color.lerp(warmSoft, other.warmSoft, t)!,
      info: Color.lerp(info, other.info, t)!,
      coolSoft: Color.lerp(coolSoft, other.coolSoft, t)!,
      deep: Color.lerp(deep, other.deep, t)!,
      deepSoft: Color.lerp(deepSoft, other.deepSoft, t)!,
      catDining: Color.lerp(catDining, other.catDining, t)!,
      catGroceries: Color.lerp(catGroceries, other.catGroceries, t)!,
      catTransport: Color.lerp(catTransport, other.catTransport, t)!,
      catRent: Color.lerp(catRent, other.catRent, t)!,
      catShopping: Color.lerp(catShopping, other.catShopping, t)!,
      catBills: Color.lerp(catBills, other.catBills, t)!,
      catEntertainment: Color.lerp(catEntertainment, other.catEntertainment, t)!,
      catHealth: Color.lerp(catHealth, other.catHealth, t)!,
      catOther: Color.lerp(catOther, other.catOther, t)!,
      surfaceAlt: Color.lerp(surfaceAlt, other.surfaceAlt, t)!,
      raised: Color.lerp(raised, other.raised, t)!,
      stage: Color.lerp(stage, other.stage, t)!,
      text3: Color.lerp(text3, other.text3, t)!,
      border2: Color.lerp(border2, other.border2, t)!,
      accentSoft: Color.lerp(accentSoft, other.accentSoft, t)!,
      accentInk: Color.lerp(accentInk, other.accentInk, t)!,
      heroA: Color.lerp(heroA, other.heroA, t)!,
      heroB: Color.lerp(heroB, other.heroB, t)!,
      heroVeil: Color.lerp(heroVeil, other.heroVeil, t)!,
      heroTrack: Color.lerp(heroTrack, other.heroTrack, t)!,
      chrome: Color.lerp(chrome, other.chrome, t)!,
      codeBg: Color.lerp(codeBg, other.codeBg, t)!,
    );
  }
}

extension AppColorsContext on BuildContext {
  AppColors get appColors => Theme.of(this).extension<AppColors>()!;
}
