// Emits lib/app/theme/app_colors.dart from the token table in
// ui-kit/BRAND_AND_UI_KIT.md §2. Generated rather than hand-written because the
// constructor, both const instances, copyWith and lerp must all list every field
// — 46 of them — and a single omission is a compile error at best and a silently
// un-lerped colour at worst.
const fs = require('fs');

// [name, light, dark, doc]
const MODULE = [
  ['finance', '0xFF0E9F6E', '0xFF0E9F6E'],
  ['spend', '0xFFC2703D', '0xFFC2703D'],
  ['habits', '0xFF3FA6A0', '0xFF3FA6A0'],
  ['tasks', '0xFF4B7BA6', '0xFF4B7BA6'],
  ['documents', '0xFFB0558E', '0xFFB0558E'],
  ['calendar', '0xFF7C6BC4', '0xFF7C6BC4'],
  ['goals', '0xFF3E7C5A', '0xFF3E7C5A'],
  ['aiAnalyser', '0xFFD9A441', '0xFFD9A441'],
  ['notes', '0xFF9A9384', '0xFF9A9384'],
];

const STATUS = [
  ['good', '0xFF0E9F6E', '0xFF34D399',
    'Success is the accent — the kit is explicit that there is no second green.'],
  ['critical', '0xFFA62F2F', '0xFFF87171', 'Kit `danger`: destructive labels, overdue, error text.'],
  ['dangerSolid', '0xFFA62F2F', '0xFFE05555', 'Ground of a filled destructive button.'],
  ['onDanger', '0xFFFFFFFF', '0xFF230A0A', 'Ink on [dangerSolid].'],
  ['dangerSoft', '0x17BE3F3F', '0x21F87171', 'Tinted error wells.'],
  ['dangerBd', '0x59BE3F3F', '0x57F87171', 'Error borders.'],
  ['warning', '0xFF8A6410', '0xFFE3B341', 'Kit `warn`: due soon, low stock, offline.'],
  ['warnSoft', '0x21D9A441', '0x24E3B341', null],
  ['warnBd', '0x4DD9A441', '0x52E3B341', null],
  ['warm', '0xFF8C4C22', '0xFFE09A6B', 'Streaks and outgoing money — the ink for the Spend hue.'],
  ['warmSoft', '0x29C2703D', '0x26E09A6B', null],
  ['info', '0xFF35618A', '0xFF8FBBE0', 'Kit `cool`: water, calendar and medicine glyphs.'],
  ['coolSoft', '0x294B7BA6', '0x268FBBE0', null],
  ['deep', '0xFF5E4FA8', '0xFFB4A7EC', 'Learn and investments.'],
  ['deepSoft', '0x297C6BC4', '0x26B4A7EC', null],
];

const CATEGORY = [
  ['catDining', '0xFF0E9F6E', '0xFF0E9F6E'],
  ['catGroceries', '0xFF3E7C5A', '0xFF3E7C5A'],
  ['catTransport', '0xFF4B7BA6', '0xFF4B7BA6'],
  ['catRent', '0xFFC2703D', '0xFFC2703D'],
  ['catShopping', '0xFFB0558E', '0xFFB0558E'],
  ['catBills', '0xFFD9A441', '0xFFD9A441'],
  ['catEntertainment', '0xFF7C6BC4', '0xFF7C6BC4'],
  ['catHealth', '0xFF3FA6A0', '0xFF3FA6A0'],
  ['catOther', '0xFF9A9384', '0xFF9A9384'],
];

const SURFACE = [
  ['surfaceAlt', '0xFFFAF6EE', '0xFF2A2823', 'Kit `surface-2`: segmented tracks, inset wells.'],
  ['raised', '0xFFFFFFFF', '0xFF26241F', 'Floating chrome — the nav pill, sheets.'],
  ['stage', '0xFFE7E2D8', '0xFF0C0B09', 'Behind the app frame; scrim fills.'],
  ['text3', '0xFF9C978C', '0xFF736F66',
    'Decorative text only — does not meet 4.5:1 in either theme. Informational\n  /// captions use `onSurfaceVariant` (the kit\'s `text-2`).'],
  ['border2', '0x0F1C1B18', '0x0DFFFFFF', 'The lighter hairline, for nested dividers.'],
  ['accentSoft', '0x1F0E9F6E', '0x2934D399', null],
  ['accentInk', '0xFF0B7C56', '0xFF6EE7B7', null],
  ['heroA', '0xFF0A6E4D', '0xFF34D399', null],
  ['heroB', '0xFF0C8058', '0xFF6EE7B7', null],
  ['heroVeil', '0x1AFFFFFF', '0x1A0C0B09', null],
  ['heroTrack', '0x47FFFFFF', '0x3D0C0B09', null],
  ['chrome', '0xFF0F0F0D', '0xFFF4F0E7', null],
  ['codeBg', '0xFFF1ECE2', '0xFF15140F', 'Ground behind monospaced code blocks.'],
];

const ALL = [...MODULE, ...STATUS, ...CATEGORY, ...SURFACE];
const names = ALL.map((f) => f[0]);

const header = `import 'package:flutter/material.dart';

/// Every colour token in the app, from \`ui-kit/BRAND_AND_UI_KIT.md\` §2.
///
/// GENERATED by \`scripts/gen_app_colors.js\` — edit the token table there, not
/// this file. The constructor, both const instances, \`copyWith\` and \`lerp\` all
/// have to list all ${names.length} fields, and hand-editing four parallel lists is how a
/// colour silently stops animating between themes.
///
/// Three rules from the kit that this encodes:
///
/// * **Semantic colours are per-theme pairs.** An ink that reads on cream is
///   invisible on near-black, so [critical], [warning], [info], [warm] and
///   [deep] each carry two values. Never reuse a light-theme hex in dark.
/// * **Success is [good], which is the accent.** There is no second green.
/// * **Category hues identify things, never state.** The \`cat*\` and module
///   entries are the same in both themes because they name a thing, not a
///   status. Use them for 14–18% alpha wells, swatches and dots; when one has to
///   carry *text*, use its semantic ink instead — [warm] for the Spend hue,
///   [info] for Water/Calendar, [deep] for Learn.
class AppColors extends ThemeExtension<AppColors> {
  const AppColors({
${names.map((n) => `    required this.${n},`).join('\n')}
  });
`;

function fieldBlock(list, heading) {
  let out = `\n  // ---- ${heading} ----\n`;
  for (const [name, , , doc] of list) {
    if (doc) out += `\n  /// ${doc}\n`;
    out += `  final Color ${name};\n`;
  }
  return out;
}

const fields =
  fieldBlock(MODULE, 'module identity') +
  fieldBlock(STATUS, 'semantic state (per-theme pairs)') +
  fieldBlock(CATEGORY, 'spend categories (identity)') +
  fieldBlock(SURFACE, 'surfaces and accents');

const palettes = `
  List<Color> get modulePalette => [
${MODULE.map((f) => `    ${f[0]},`).join('\n')}
  ];

  List<Color> get spendCategoryPalette => [
${CATEGORY.map((f) => `    ${f[0]},`).join('\n')}
  ];

  /// Kit \`accent\` in light. Feeds \`ColorScheme.fromSeed\`.
  static const seed = Color(0xFF0E9F6E);
`;

function instance(name, index) {
  return `
  static const ${name} = AppColors(
${ALL.map((f) => `    ${f[0]}: Color(${f[index]}),`).join('\n')}
  );
`;
}

const copyWith = `
  @override
  AppColors copyWith({
${names.map((n) => `    Color? ${n},`).join('\n')}
  }) {
    return AppColors(
${names.map((n) => `      ${n}: ${n} ?? this.${n},`).join('\n')}
    );
  }
`;

const lerp = `
  @override
  AppColors lerp(ThemeExtension<AppColors>? other, double t) {
    if (other is! AppColors) return this;
    return AppColors(
${names.map((n) => `      ${n}: Color.lerp(${n}, other.${n}, t)!,`).join('\n')}
    );
  }
}

extension AppColorsContext on BuildContext {
  AppColors get appColors => Theme.of(this).extension<AppColors>()!;
}
`;

fs.writeFileSync(
  'lib/app/theme/app_colors.dart',
  header + fields + palettes + instance('light', 1) + instance('dark', 2) + copyWith + lerp,
);
console.log(`generated ${names.length} tokens`);
